using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace RotaryMonitor
{
    /// <summary>Self-contained localization. Strings are compiled into the
    /// assembly (no MRT/resources.pri dependency) for reliable behavior in
    /// unpackaged self-contained builds.</summary>
    public static class L
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Tables =
            new Dictionary<string, Dictionary<string, string>>
            {
                { "en-US", new Dictionary<string, string>
                {
                { "AppTitle.Title", "Rotary" },
                { "SerialHeader.Text", "Serial" },
                { "PortLabel.Text", "Port:" },
                { "RefreshButton.Content", "Refresh" },
                { "StartButton.Content", "Start monitoring" },
                { "SensorButton.Content", "Sensor view..." },
                { "StatusText.Text", "Stopped" },
                { "WallpaperHeader.Text", "Wallpaper" },
                { "ModeBothRadio.Content", "All monitors" },
                { "ModeMainRadio.Content", "Rotation monitor only" },
                { "WallpaperHint", "Each monitor gets the image matching its own orientation — landscape for horizontal, portrait for vertical." },
                { "LandscapeLabel.Text", "Landscape:" },
                { "PortraitLabel.Text", "Portrait:" },
                { "SecondaryLabel.Text", "Secondary color:" },
                { "MappingHeader.Text", "Mapping" },
                { "State1Label.Text", "Portrait direction 1 -> rotate to:" },
                { "State3Label.Text", "Portrait direction 2 -> rotate to:" },
                { "MappingHint", "Calibration sets the accessory’s mounting offset. Upright = 0°, right edge down = 90°, upside down = 180°, left edge down = 270°." },
                { "CalButton", "Calibrate..." },
                { "CalStatus", "Mounting offset: {0}°" },
                { "CalNotCalibrated", "Not calibrated (default 0°)" },
                { "CalTitle", "Calibrate mounting orientation" },
                { "CalIntro", "Attach the accessory to the monitor, keeping the monitor horizontal (landscape)." },
                { "CalChoose", "Choose the direction you will rotate the monitor, rotate it to that position, then press Capture." },
                { "CalCapture", "Capture orientation" },
                { "CalDone", "Calibration complete. Mounting offset: {0}°" },
                { "CalLive", "Current angle:" },
                { "CalFinish", "Finish" },
                { "CalNoData", "Waiting for sensor data..." },
                { "TestHeader.Text", "Test (applies rotation immediately)" },
                { "TestLandscapeButton.Content", "Landscape" },
                { "TestPortrait90Button.Content", "Portrait 90" },
                { "TestPortrait270Button.Content", "Portrait 270" },
                { "TestFlippedButton.Content", "Flipped 180" },
                { "ApplyOnStartupCheck.Content", "Apply current orientation when the app starts" },
                { "LanguageLabel.Text", "Language:" },
                { "SaveButton.Content", "Save settings" },
                { "LogHeader.Text", "Log" },
                { "OptionsHeader", "Options" },
                { "StartWithWindows", "Start with Windows" },
                { "AppSubtitle", "Monitor rotation switch · D1 Mini + BMI160" },
                { "MsgStartupOn", "Start with Windows enabled." },
                { "MsgStartupOff", "Start with Windows disabled." },
                { "MsgPickPortTitle", "No COM port" },
                { "MsgAutoPickedPort", "Auto-picked port {0}." },
                { "MsgCloseSensorFirst", "Close the sensor view before starting monitoring." },
                { "NavMonitor", "Monitor" },
                { "NavWallpaper", "Wallpaper" },
                { "NavOptions", "Options" },
                { "NavLog", "Log" },
                { "AutoRestart", "Auto-restart on crash" },
                { "RestartNow", "Restart now" },
                { "MsgAutoRestartOn", "Auto-restart on crash enabled." },
                { "MsgAutoRestartOff", "Auto-restart on crash disabled." },
                { "RotateTargetLabel", "Rotation target:" },
                { "PrimaryMonitor", "primary" },
                { "Deg180", "180°" },
                { "SensorFlipped", "Flipped (180°)" },
                { "SensorNote.Text", "Read-only view — Windows rotation / wallpaper are NOT changed." },
                { "StatusStopped", "Stopped" },
                { "StatusConnected", "Connected: {0}" },
                { "StatusDisconnected", "Disconnected" },
                { "PortStart", "Start monitoring" },
                { "PortStop", "Stop monitoring" },
                { "Deg90", "90°" },
                { "Deg270", "270°" },
                { "LangSystem", "System default" },
                { "MsgSettingsSaved", "Settings saved to {0}" },
                { "MsgPorts", "Ports: {0}" },
                { "MsgStopping", "Stopping..." },
                { "MsgOpenSensor", "Opening read-only sensor view on {0} (no changes applied)." },
                { "MsgPickPortFirst", "Pick a COM port first." },
                { "MsgStoppingSerial", "Stopping monitoring to free the serial port..." },
                { "MsgSerialOpen", "Serial {0} open" },
                { "MsgSerialError", "Serial error: {0}" },
                { "MsgBaseline", "Baseline state {0} captured (apply-on-startup off)" },
                { "MsgApplyingRotation", "Applying rotation dmdo={0}" },
                { "MsgAppliedLandscape", "Applied landscape" },
                { "MsgAppliedPortrait", "Applied portrait" },
                { "MsgWallpaperNotFound", "Wallpaper not found: {0}" },
                { "MsgWallpaperBoth", "Wallpaper (both): {0}" },
                { "MsgWallpaperMain", "Wallpaper (main only): {0}" },
                { "MsgApplyFailed", "Apply failed: {0}" },
                { "MsgDispChange", "ChangeDisplaySettingsEx returned {0}" },
                { "MsgRestart", "Restart" },
                { "MsgCancel", "Cancel" },
                { "MsgLanguageChangedTitle", "Restart required" },
                { "MsgLanguageChangedBody", "The language change applies after restart. Restart now?" },
                { "SensorTitle", "Sensor test (read-only)" },
                { "SensorLandscape", "Landscape" },
                { "SensorPortrait90", "Portrait (90°)" },
                { "SensorPortrait270", "Portrait (270°)" },
                { "SensorBetween", "Between positions" },
                { "SensorNoData", "no data" },
                { "SensorConnecting", "connecting to {0}..." },
                { "SensorConnected", "connected: {0}" },
                { "SensorClosed", "closed" },
                { "SensorError", "serial error: {0}" },
                { "PortConnect", "Connect" },
                { "PortDisconnect", "Disconnect" },
                { "MsgConnectFirst", "Connect to a COM port first." },
                { "AutoConnect", "Auto-connect on startup" },
                { "NavAbout", "About" },
                { "AboutVersion", "Version: {0}" },
                { "AboutRepo", "GitHub repository" },
                { "CheckUpdates", "Check for updates" },
                { "UpToDate", "You have the latest version." },
                { "UpdateAvailable", "Version {0} is available." },
                { "UpdateFailed", "Could not check for updates." },
                { "AboutNotConfigured", "Set your repository URL in the source to enable update checks." },
                { "TrayShow", "Show" },
                { "TrayExit", "Exit" },
                { "TrayHint", "Rotary is still running in the tray." },
                { "ExitButton", "Exit" },
                { "CalStep1", "Step 1 of 3 — Keep the monitor horizontal (landscape), then press Save baseline." },
                { "CalBaseline", "Save baseline" },
                { "CalBaselineDone", "Baseline captured: {0}°" },
                { "CalStep2", "Step 2 of 3 — Choose the rotation direction, then rotate the monitor to that position." },
                { "CalDirCW", "90° — clockwise (right edge down)" },
                { "CalDirCCW", "270° — counterclockwise (left edge down)" },
                { "CalStep3", "Step 3 of 3 — Press Save rotation." },
                { "CalSaveRot", "Save rotation" },
                { "CalVerify", "Detected rotation: {0}° (expected {1}°)" },
                { "CalMismatch", "Mismatch — detected {0}°, expected {1}°. Check the direction and try again." },
                } },
                { "zh-CN", new Dictionary<string, string>
                {
                { "AppTitle.Title", "Rotary" },
                { "SerialHeader.Text", "串口" },
                { "PortLabel.Text", "端口：" },
                { "RefreshButton.Content", "刷新" },
                { "StartButton.Content", "开始监控" },
                { "SensorButton.Content", "传感器视图..." },
                { "StatusText.Text", "已停止" },
                { "WallpaperHeader.Text", "壁纸" },
                { "ModeBothRadio.Content", "所有显示器" },
                { "ModeMainRadio.Content", "仅旋转显示器" },
                { "WallpaperHint", "每台显示器会使用与自身方向匹配的图片——横屏用横屏图，竖屏用竖屏图。" },
                { "LandscapeLabel.Text", "横屏：" },
                { "PortraitLabel.Text", "竖屏：" },
                { "SecondaryLabel.Text", "辅助颜色：" },
                { "MappingHeader.Text", "映射" },
                { "State1Label.Text", "竖屏方向 1 → 旋转为：" },
                { "State3Label.Text", "竖屏方向 2 → 旋转为：" },
                { "MappingHint", "校准可设置传感器安装偏移。横屏为 0°，右边缘朝下为 90°，倒置为 180°，左边缘朝下为 270°。" },
                { "CalButton", "校准..." },
                { "CalStatus", "安装偏移：{0}°" },
                { "CalNotCalibrated", "未校准（默认 0°）" },
                { "CalTitle", "校准安装方向" },
                { "CalIntro", "将传感器装置固定到显示器上，保持显示器为横屏。" },
                { "CalChoose", "选择将要旋转的方向，旋转显示器到该位置，然后点击“捕获”。" },
                { "CalCapture", "捕获方向" },
                { "CalDone", "校准完成。安装偏移：{0}°" },
                { "CalLive", "当前角度：" },
                { "CalFinish", "完成" },
                { "CalNoData", "正在等待传感器数据..." },
                { "TestHeader.Text", "测试（立即旋转）" },
                { "TestLandscapeButton.Content", "横屏" },
                { "TestPortrait90Button.Content", "竖屏 90" },
                { "TestPortrait270Button.Content", "竖屏 270" },
                { "TestFlippedButton.Content", "翻转 180" },
                { "ApplyOnStartupCheck.Content", "启动时应用当前方向" },
                { "LanguageLabel.Text", "语言：" },
                { "SaveButton.Content", "保存设置" },
                { "LogHeader.Text", "日志" },
                { "OptionsHeader", "选项" },
                { "StartWithWindows", "随 Windows 启动" },
                { "AppSubtitle", "显示器旋转切换 · D1 Mini + BMI160" },
                { "MsgStartupOn", "已启用随 Windows 启动。" },
                { "MsgStartupOff", "已禁用随 Windows 启动。" },
                { "MsgPickPortTitle", "没有串口" },
                { "MsgAutoPickedPort", "已自动选择串口 {0}。" },
                { "MsgCloseSensorFirst", "请先关闭传感器视图再开始监控。" },
                { "NavMonitor", "显示器设置" },
                { "NavWallpaper", "壁纸" },
                { "NavOptions", "选项" },
                { "NavLog", "日志" },
                { "AutoRestart", "崩溃时自动重启" },
                { "RestartNow", "立即重启" },
                { "MsgAutoRestartOn", "已启用崩溃时自动重启。" },
                { "MsgAutoRestartOff", "已禁用崩溃时自动重启。" },
                { "RotateTargetLabel", "旋转目标：" },
                { "PrimaryMonitor", "主屏" },
                { "Deg180", "180°" },
                { "SensorFlipped", "翻转（180°）" },
                { "SensorNote.Text", "只读视图 — 不会旋转显示器或更改壁纸。" },
                { "StatusStopped", "已停止" },
                { "StatusConnected", "已连接：{0}" },
                { "StatusDisconnected", "未连接" },
                { "PortStart", "开始监控" },
                { "PortStop", "停止监控" },
                { "Deg90", "90°" },
                { "Deg270", "270°" },
                { "LangSystem", "系统默认" },
                { "MsgSettingsSaved", "设置已保存到 {0}" },
                { "MsgPorts", "端口：{0}" },
                { "MsgStopping", "正在停止..." },
                { "MsgOpenSensor", "正在打开只读传感器视图 {0}（不应用任何更改）。" },
                { "MsgPickPortFirst", "请先选择串口。" },
                { "MsgStoppingSerial", "正在停止监控以释放串口..." },
                { "MsgSerialOpen", "串口 {0} 已打开" },
                { "MsgSerialError", "串口错误：{0}" },
                { "MsgBaseline", "已捕获初始状态 {0}（未开启启动应用）" },
                { "MsgApplyingRotation", "正在应用旋转 dmdo={0}" },
                { "MsgAppliedLandscape", "已应用横屏" },
                { "MsgAppliedPortrait", "已应用竖屏" },
                { "MsgWallpaperNotFound", "壁纸文件不存在：{0}" },
                { "MsgWallpaperBoth", "壁纸（两台）：{0}" },
                { "MsgWallpaperMain", "壁纸（仅主屏）：{0}" },
                { "MsgApplyFailed", "应用失败：{0}" },
                { "MsgDispChange", "ChangeDisplaySettingsEx 返回 {0}" },
                { "MsgRestart", "立即重启" },
                { "MsgCancel", "取消" },
                { "MsgLanguageChangedTitle", "需要重启" },
                { "MsgLanguageChangedBody", "语言将在重启后生效。立即重启？" },
                { "SensorTitle", "传感器测试（只读）" },
                { "SensorLandscape", "横屏" },
                { "SensorPortrait90", "竖屏（90°）" },
                { "SensorPortrait270", "竖屏（270°）" },
                { "SensorBetween", "中间位置" },
                { "SensorNoData", "无数据" },
                { "SensorConnecting", "正在连接 {0}..." },
                { "SensorConnected", "已连接：{0}" },
                { "SensorClosed", "已关闭" },
                { "SensorError", "串口错误：{0}" },
                { "PortConnect", "连接" },
                { "PortDisconnect", "断开" },
                { "MsgConnectFirst", "请先连接串口。" },
                { "AutoConnect", "启动时自动连接" },
                { "NavAbout", "关于" },
                { "AboutVersion", "版本：{0}" },
                { "AboutRepo", "GitHub 仓库" },
                { "CheckUpdates", "检查更新" },
                { "UpToDate", "已是最新版本。" },
                { "UpdateAvailable", "发现新版本 {0}。" },
                { "UpdateFailed", "无法检查更新。" },
                { "AboutNotConfigured", "请在源码中设置仓库地址以启用更新检查。" },
                { "TrayShow", "显示" },
                { "TrayExit", "退出" },
                { "TrayHint", "Rotary 仍在托盘运行中。" },
                { "ExitButton", "退出" },
                { "CalStep1", "第 1 步（共 3 步）——保持显示器水平（横屏），然后点击“保存基准”。" },
                { "CalBaseline", "保存基准" },
                { "CalBaselineDone", "已捕获基准：{0}°" },
                { "CalStep2", "第 2 步（共 3 步）——选择旋转方向，然后将显示器旋转到该位置。" },
                { "CalDirCW", "90° —— 顺时针（右边缘朝下）" },
                { "CalDirCCW", "270° —— 逆时针（左边缘朝下）" },
                { "CalStep3", "第 3 步（共 3 步）——点击“保存旋转”。" },
                { "CalSaveRot", "保存旋转" },
                { "CalVerify", "检测到旋转：{0}°（预期 {1}°）" },
                { "CalMismatch", "不匹配——检测到 {0}°，预期 {1}°。请检查方向后重试。" },
                } },
                { "ja-JP", new Dictionary<string, string>
                {
                { "AppTitle.Title", "Rotary" },
                { "SerialHeader.Text", "シリアル" },
                { "PortLabel.Text", "ポート：" },
                { "RefreshButton.Content", "更新" },
                { "StartButton.Content", "監視開始" },
                { "SensorButton.Content", "センサービュー..." },
                { "StatusText.Text", "停止中" },
                { "WallpaperHeader.Text", "壁紙" },
                { "ModeBothRadio.Content", "すべてのモニター" },
                { "ModeMainRadio.Content", "回転モニターのみ" },
                { "WallpaperHint", "各モニターは自分の向きに合った画像を使用します——横向きは横向き用、縦向きは縦向き用です。" },
                { "LandscapeLabel.Text", "横向き：" },
                { "PortraitLabel.Text", "縦向き：" },
                { "SecondaryLabel.Text", "背景色：" },
                { "MappingHeader.Text", "マッピング" },
                { "State1Label.Text", "縦方向 1 → 回転先：" },
                { "State3Label.Text", "縦方向 2 → 回転先：" },
                { "MappingHint", "校正でセンサーの取り付けオフセットを設定します。横向き = 0°、右端が下 = 90°、逆さま = 180°、左端が下 = 270°。" },
                { "CalButton", "校正..." },
                { "CalStatus", "取り付けオフセット：{0}°" },
                { "CalNotCalibrated", "未校正（既定 0°）" },
                { "CalTitle", "取り付け方向の校正" },
                { "CalIntro", "アクセサリーをモニターに取り付け、モニターを横向き（ランドスケープ）に保ちます。" },
                { "CalChoose", "回転させる方向を選択し、その位置までモニターを回転して、“取得”を押します。" },
                { "CalCapture", "方向を取得" },
                { "CalDone", "校正完了。取り付けオフセット：{0}°" },
                { "CalLive", "現在の角度：" },
                { "CalFinish", "完了" },
                { "CalNoData", "センサーデータを待っています..." },
                { "TestHeader.Text", "テスト（即時回転）" },
                { "TestLandscapeButton.Content", "横向き" },
                { "TestPortrait90Button.Content", "縦90" },
                { "TestPortrait270Button.Content", "縦270" },
                { "TestFlippedButton.Content", "反転180" },
                { "ApplyOnStartupCheck.Content", "起動時に現在の向きを適用" },
                { "LanguageLabel.Text", "言語：" },
                { "SaveButton.Content", "設定を保存" },
                { "LogHeader.Text", "ログ" },
                { "OptionsHeader", "オプション" },
                { "StartWithWindows", "Windows と一緒に起動" },
                { "AppSubtitle", "モニター回転スイッチ · D1 Mini + BMI160" },
                { "MsgStartupOn", "Windows 起動を有効にしました。" },
                { "MsgStartupOff", "Windows 起動を無効にしました。" },
                { "MsgPickPortTitle", "COMポートがありません" },
                { "MsgAutoPickedPort", "ポート {0} を自動選択しました。" },
                { "MsgCloseSensorFirst", "監視を開始する前にセンサービューを閉じてください。" },
                { "NavMonitor", "モニター" },
                { "NavWallpaper", "壁紙" },
                { "NavOptions", "オプション" },
                { "NavLog", "ログ" },
                { "AutoRestart", "クラッシュ時に自動再起動" },
                { "RestartNow", "今すぐ再起動" },
                { "MsgAutoRestartOn", "クラッシュ時の自動再起動を有効にしました。" },
                { "MsgAutoRestartOff", "クラッシュ時の自動再起動を無効にしました。" },
                { "RotateTargetLabel", "回転対象：" },
                { "PrimaryMonitor", "メイン" },
                { "Deg180", "180°" },
                { "SensorFlipped", "反転（180°）" },
                { "SensorNote.Text", "読み取り専用ビュー — 回転や壁紙は変更されません。" },
                { "StatusStopped", "停止中" },
                { "StatusConnected", "接続中：{0}" },
                { "StatusDisconnected", "未接続" },
                { "PortStart", "監視開始" },
                { "PortStop", "監視停止" },
                { "Deg90", "90°" },
                { "Deg270", "270°" },
                { "LangSystem", "システム既定" },
                { "MsgSettingsSaved", "設定を保存しました：{0}" },
                { "MsgPorts", "ポート：{0}" },
                { "MsgStopping", "停止中..." },
                { "MsgOpenSensor", "読み取り専用のセンサービューを開きます：{0}（変更は適用されません）" },
                { "MsgPickPortFirst", "まずCOMポートを選択してください。" },
                { "MsgStoppingSerial", "シリアルポートを解放するため監視を停止しています..." },
                { "MsgSerialOpen", "シリアル {0} を開きました" },
                { "MsgSerialError", "シリアルエラー：{0}" },
                { "MsgBaseline", "初期状態 {0} を取得しました（起動時適用オフ）" },
                { "MsgApplyingRotation", "回転を適用中 dmdo={0}" },
                { "MsgAppliedLandscape", "横向きを適用しました" },
                { "MsgAppliedPortrait", "縦向きを適用しました" },
                { "MsgWallpaperNotFound", "壁紙が見つかりません：{0}" },
                { "MsgWallpaperBoth", "壁紙（両方）：{0}" },
                { "MsgWallpaperMain", "壁紙（メインのみ）：{0}" },
                { "MsgApplyFailed", "適用に失敗しました：{0}" },
                { "MsgDispChange", "ChangeDisplaySettingsEx の戻り値 {0}" },
                { "MsgRestart", "再起動" },
                { "MsgCancel", "キャンセル" },
                { "MsgLanguageChangedTitle", "再起動が必要です" },
                { "MsgLanguageChangedBody", "言語は再起動後に適用されます。すぐに再起動しますか？" },
                { "SensorTitle", "センサーテスト（読み取り専用）" },
                { "SensorLandscape", "横向き" },
                { "SensorPortrait90", "縦向き（90°）" },
                { "SensorPortrait270", "縦向き（270°）" },
                { "SensorBetween", "中間位置" },
                { "SensorNoData", "データなし" },
                { "SensorConnecting", "{0} に接続中..." },
                { "SensorConnected", "接続済み：{0}" },
                { "SensorClosed", "終了" },
                { "SensorError", "シリアルエラー：{0}" },
                { "PortConnect", "接続" },
                { "PortDisconnect", "切断" },
                { "MsgConnectFirst", "先にCOMポートへ接続してください。" },
                { "AutoConnect", "起動時に自動接続" },
                { "NavAbout", "バージョン情報" },
                { "AboutVersion", "バージョン：{0}" },
                { "AboutRepo", "GitHub リポジトリ" },
                { "CheckUpdates", "更新を確認" },
                { "UpToDate", "最新バージョンです。" },
                { "UpdateAvailable", "バージョン {0} が利用可能です。" },
                { "UpdateFailed", "更新を確認できませんでした。" },
                { "AboutNotConfigured", "更新確認を有効にするにはソースでリポジトリURLを設定してください。" },
                { "TrayShow", "表示" },
                { "TrayExit", "終了" },
                { "TrayHint", "Rotary はトレイで実行中です。" },
                { "ExitButton", "終了" },
                { "CalStep1", "手順 1/3 — モニターを横向きに保ち、「基準を保存」を押してください。" },
                { "CalBaseline", "基準を保存" },
                { "CalBaselineDone", "基準を取得しました：{0}°" },
                { "CalStep2", "手順 2/3 — 回転方向を選び、モニターをその位置まで回転してください。" },
                { "CalDirCW", "90° — 時計回り（右端が下）" },
                { "CalDirCCW", "270° — 反時計回り（左端が下）" },
                { "CalStep3", "手順 3/3 — 「回転を保存」を押してください。" },
                { "CalSaveRot", "回転を保存" },
                { "CalVerify", "検出した回転：{0}°（予想 {1}°）" },
                { "CalMismatch", "不一致 — 検出 {0}°、予想 {1}°。方向を確認してやり直してください。" },
                } },
            };

        private static string _lang = "";

        public static void Init(string langOverride)
        {
            _lang = langOverride ?? "";
        }

        public static string Get(string key)
        {
            string lang = string.IsNullOrEmpty(_lang) ? SystemLanguage() : _lang;
            Dictionary<string, string> table;
            if (Tables.TryGetValue(lang, out table))
            {
                string v;
                if (table.TryGetValue(key, out v))
                    return v;
            }
            if (lang != "en-US" && Tables["en-US"].TryGetValue(key, out var en))
                return en;
            return key;
        }

        private static string SystemLanguage()
        {
            // Robust for unpackaged apps: read the OS UI language via P/Invoke.
            try
            {
                ushort lang = GetUserDefaultUILanguage();
                int primary = lang & 0x3FF;
                if (primary == 0x04) return "zh-CN";   // Chinese
                if (primary == 0x11) return "ja-JP";   // Japanese
                if (primary == 0x09) return "en-US";   // English
            }
            catch { }

            try
            {
                foreach (var l in Windows.Globalization.ApplicationLanguages.Languages)
                {
                    if (l.StartsWith("zh", StringComparison.OrdinalIgnoreCase)) return "zh-CN";
                    if (l.StartsWith("ja", StringComparison.OrdinalIgnoreCase)) return "ja-JP";
                    if (l.StartsWith("en", StringComparison.OrdinalIgnoreCase)) return "en-US";
                }
            }
            catch { }
            return "en-US";
        }

        [DllImport("kernel32.dll")]
        private static extern ushort GetUserDefaultUILanguage();
    }
}
